name: dev - Build

on:
  push:
    branches:
    - dev_sprint01
    - dev_sprint02
    - dev_sprint03
  pull_request:
    branches:
    - dev_sprint01
    - dev_sprint02
    - dev_sprint03

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
